# A Docker Compose application with Moqui, MySQL, OpenSearch, OpenSearch Dashboards, and virtual hosting through
# nginx-proxy supporting multiple moqui instances on different hostnames.

# Run with something like this for detached mode:
# $ docker compose -f moqui-mysql-compose.yml -p moqui up -d
# Or to copy runtime directories for mounted volumes, set default settings, etc use something like this:
# $ ./compose-run.sh moqui-mysql-compose.yml
# This sets the project/app name to 'moqui' and the network will be 'moqui_default', to be used by external moqui containers

# Test locally by adding the virtual host to /etc/hosts or with something like:
# $ curl -H "Host: moqui.local" localhost/Login

# To run an additional instance of moqui run something like this (but with
# many more arguments for volume mapping, db setup, etc):
# $ docker run -e VIRTUAL_HOST=moqui2.local --name moqui2_local --network moqui_default moqui

# To import data from the docker host using port 3306 mapped for 127.0.0.1 only use something like this:
# $ mysql -p -u root -h 127.0.0.1 moqui < mysql-export.sql

version: "2"
services:
  nginx-proxy:
    # For documentation on SSL and other settings see:
    # https://github.com/jwilder/nginx-proxy
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # note: .crt, .key, and .dhparam.pem files start with the domain name in VIRTUAL_HOST (ie 'moqui.local.*') or use CERT_NAME env var
      - ./certs:/etc/nginx/certs
      - ./nginx/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf
    environment:
      # change this for the default host to use when accessing directly by IP, etc
      - DEFAULT_HOST=moqui.local
      # use SSL_POLICY to disable TLSv1.0, etc in nginx-proxy
      - SSL_POLICY=AWS-TLS-1-1-2017-01

  moqui-server:
    image: moqui
    container_name: moqui-server
    command: conf=conf/MoquiProductionConf.xml
    restart: always
    links:
      - moqui-database
      - moqui-search
    volumes:
      - ./runtime/conf:/opt/moqui/runtime/conf
      - ./runtime/lib:/opt/moqui/runtime/lib
      - ./runtime/classes:/opt/moqui/runtime/classes
      - ./runtime/ecomponent:/opt/moqui/runtime/ecomponent
      - ./runtime/log:/opt/moqui/runtime/log
      - ./runtime/txlog:/opt/moqui/runtime/txlog
      - ./runtime/sessions:/opt/moqui/runtime/sessions
      # this one isn't needed when not using H2/etc: - ./runtime/db:/opt/moqui/runtime/db
    environment:
      - "JAVA_TOOL_OPTIONS=-Xms1024m -Xmx1024m"
      - instance_purpose=production
      - entity_ds_db_conf=mysql8
      - entity_ds_host=moqui-database
      - entity_ds_port=3306
      - entity_ds_database=moqui
      # NOTE: using root user because for TX recovery MySQL requires the 'XA_RECOVER_ADMIN' and in version 8 that must be granted explicitly
      - entity_ds_user=root
      - entity_ds_password=moquiroot
      - entity_ds_crypt_pass='DEFAULT_CHANGE_ME!!!'
      # configuration for ElasticFacade.ElasticClient, make sure the old moqui-elasticsearch component is NOT included in the Moqui build
      - elasticsearch_url=https://moqui-search:9200
      # prefix for index names, use something distinct and not 'moqui_' or 'mantle_' which match the beginning of OOTB index names
      - elasticsearch_index_prefix=default_
      - elasticsearch_user=admin
      - elasticsearch_password=admin
      # CHANGE ME - note that VIRTUAL_HOST is for nginx-proxy so it picks up this container as one it should reverse proxy
      # this can be a comma separate list of hosts like 'example.com,www.example.com'
      - VIRTUAL_HOST=moqui.local
      # moqui will accept traffic from other hosts but these are the values used for URL writing when specified:
      # - webapp_http_host=moqui.local
      - webapp_http_port=80
      - webapp_https_port=443
      - webapp_https_enabled=true
      # nginx-proxy populates X-Real-IP with remote_addr by default, better option for outer proxy than X-Forwarded-For which defaults to proxy_add_x_forwarded_for
      - webapp_client_ip_header=X-Real-IP
      - default_locale=en_US
      - default_time_zone=US/Pacific

  moqui-database:
    image: mysql:8.0
    container_name: moqui-database
    restart: always
    ports:
     # change this as needed to bind to any address or even comment to not expose port outside containers
     - 127.0.0.1:3306:3306
    volumes:
     # edit these as needed to map configuration and data storage
     - ./db/mysql/data:/var/lib/mysql
     # - /my/mysql/conf.d:/etc/mysql/conf.d
    environment:
     - MYSQL_ROOT_PASSWORD=moquiroot
     - MYSQL_DATABASE=moqui
     - MYSQL_USER=moqui
     - MYSQL_PASSWORD=moqui

  moqui-search:
    image: opensearchproject/opensearch:2.4.0
    container_name: moqui-search
    restart: always
    ports:
      # change this as needed to bind to any address or even comment to not expose port outside containers
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    volumes:
      # edit these as needed to map configuration and data storage
      - ./opensearch/data:/usr/share/opensearch/data
      # - ./opensearch/config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      # - ./opensearch/logs:/usr/share/opensearch/logs
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - network.host=_site_
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.4.0
    container_name: opensearch-dashboards
    links:
      - moqui-search
    ports:
      - 5601:5601
    expose:
      - 127.0.0.1:5601:5601
    environment:
      OPENSEARCH_HOSTS: '["https://moqui-search:9200"]'
