# A Docker Compose application with moqui, postgres, and virtual hosting through
# nginx-proxy supporting multiple moqui instances on different hosts.

# Run with something like this for detached mode:
# $ docker-compose -f moqui-ng-pg-compose.yml -p moqui up -d
# Or to copy runtime directories for mounted volumes, set default settings, etc use something like this:
# $ ./compose-run.sh moqui-ng-pg-compose.yml
# This sets the project/app name to 'moqui' and the network will be 'moqui_default', to be used by external moqui containers

# Test locally by adding the virtual host to /etc/hosts or with something like:
# $ curl -H "Host: moqui.local" localhost/Login

# To run an additional instance of moqui run something like this (but with
# many more arguments for volume mapping, db setup, etc):
# $ docker run -e VIRTUAL_HOST=moqui2.local --name moqui2_local --network moqui_default moqui

version: "2"
services:
  nginx-proxy:
    # For documentation on SSL and other settings see:
    # https://github.com/jwilder/nginx-proxy
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      # - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # - /path/to/certs:/etc/nginx/certs
  moqui-server:
    image: moqui
    container_name: moqui-server
    command: conf=conf/MoquiProductionConf.xml
    restart: unless-stopped
    links:
     - moqui-database
    volumes:
     - ./runtime/conf:/opt/moqui/runtime/conf
     - ./runtime/lib:/opt/moqui/runtime/lib
     - ./runtime/classes:/opt/moqui/runtime/classes
     - ./runtime/ecomponent:/opt/moqui/runtime/ecomponent
     - ./runtime/log:/opt/moqui/runtime/log
     - ./runtime/txlog:/opt/moqui/runtime/txlog
     # this one isn't needed: - ./runtime/db:/opt/moqui/runtime/db
     - ./runtime/elasticsearch:/opt/moqui/runtime/elasticsearch
    environment:
     - entity_ds_db_conf=postgres
     - entity_ds_host=moqui-database
     - entity_ds_port=5432
     - entity_ds_database=moqui
     - entity_ds_schema=public
     - entity_ds_user=moqui
     - entity_ds_password=moqui
     - entity_ds_crypt_pass='MoquiDefaultPassword:CHANGEME'
     # CHANGE ME - note that VIRTUAL_HOST is for nginx-proxy so it picks up this container as one it should reverse proxy
     - VIRTUAL_HOST=moqui.local
     - webapp_http_host=moqui.local
     - webapp_http_port=80
     # - webapp_https_port=443
     # - webapp_https_enabled=true

  moqui-database:
    image: postgres:9.5
    container_name: moqui-database
    restart: unless-stopped
    # uncomment this to expose the port for use outside other containers
    # ports:
    #  - 5432:5432
    # edit these as needed to map configuration and data storage
    volumes:
     - ./db/postgres/data:/var/lib/postgresql/data
    environment:
     - POSTGRES_DB=moqui
     - POSTGRES_DB_SCHEMA=public
     - POSTGRES_USER=moqui
     - POSTGRES_PASSWORD=moqui
     # PGDATA, POSTGRES_INITDB_ARGS
