version: "3.5"
services:
  pg-dump-database:
    image: postgres:14.1-alpine
    container_name: dev-postgres
    volumes:
      - ./../../db/dump:/tmp
    environment:
      POSTGRES_USER: moqui
      POSTGRES_DB: moqui
      POSTGRES_PASSWORD: postgres
      PGPORT: 5432
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5432" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - ars-int
    ports:
     - "0.0.0.0:5432:5432"

networks:
  ars-int:
    external: true