name: custom-modules-unit-tests
on: [push]
jobs:
  component-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 13
          distribution: adopt
      - name: Checkout runtime
        uses: actions/checkout@v2
        with:
          repository: dataquest-dev/moqui-runtime
          path: './runtime'
          ref: production
      - name: Checkout moqui-closure-api
        uses: actions/checkout@v2
        with:
          repository: dataquest-dev/moqui-closure-api
          ssh-key: ${{ secrets.DK_MOQUI_CLOSURE_API }}
          path: './runtime/component/moqui-closure-api'
          ref: master
      - name: Prep - clean database
        run: ./gradlew cleanDb
      - name: Prep - load database
        run: ./gradlew load
      - name: Run unit tests on all components
        run: ./gradlew compTest
