name: whole-component tests
on: [push]
jobs:
  closure-api-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 13
          distribution: adopt
      - name: Checkout runtime
        uses: actions/checkout@v2
        with:
          repository: dataquest-dev/moqui-runtime
          path: './runtime'
          ref: dtq-dev
      - name: Checkout moqui-closure-api
        uses: actions/checkout@v2
        with:
          repository: dataquest-dev/moqui-closure-api
          ssh-key: ${{ secrets.DK_MOQUI_CLOSURE_API }}
          path: './runtime/component/moqui-closure-api'
          ref: dtq-dev
      - name: Prep - clean database
        run: ./gradlew cleanDb
      - name: Prep - load database
        run: ./gradlew load
      - name: Run unit tests on all components
        run: ./gradlew compTest

  acc-extractor-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 13
          distribution: adopt
      - name: Checkout runtime
        uses: actions/checkout@v2
        with:
          repository: dataquest-dev/moqui-runtime
          path: './runtime'
          ref: dtq-dev
      - name: Checkout moqui-acc-extractor
        uses: actions/checkout@v2
        with:
          repository: dataquest-dev/moqui-acc-extractor
          ssh-key: ${{ secrets.DK_MOQUI_ACC_EXTRACTOR }}
          path: './runtime/component/moqui-acc-extractor'
          ref: dtq-dev
      - name: Prep - clean database
        run: ./gradlew cleanDb
      - name: Prep - load database
        run: ./gradlew load
      - name: Run unit tests on all components
        run: ./gradlew compTest

  projects-api-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 13
          distribution: adopt
      - name: Checkout runtime
        uses: actions/checkout@v2
        with:
          repository: dataquest-dev/moqui-runtime
          path: './runtime'
          ref: dtq-dev
      - name: Checkout moqui-projects-api
        uses: actions/checkout@v2
        with:
          repository: dataquest-dev/moqui-projects-api
          ssh-key: ${{ secrets.DK_MOQUI_PROJECTS_API }}
          path: './runtime/component/moqui-projects-api'
          ref: dtq-dev
      - name: Prep - clean database
        run: ./gradlew cleanDb
      - name: Prep - load database
        run: ./gradlew load
      - name: Run unit tests on all components
        run: ./gradlew compTest

  all-components-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 13
          distribution: adopt
      - name: Checkout runtime
        uses: actions/checkout@v2
        with:
          repository: dataquest-dev/moqui-runtime
          path: './runtime'
          ref: dtq-dev
      - name: Checkout moqui-closure-api
        uses: actions/checkout@v2
        with:
          repository: dataquest-dev/moqui-closure-api
          ssh-key: ${{ secrets.DK_MOQUI_CLOSURE_API }}
          path: './runtime/component/moqui-closure-api'
          ref: dtq-dev
      - name: Checkout moqui-acc-extractor
        uses: actions/checkout@v2
        with:
          repository: dataquest-dev/moqui-acc-extractor
          ssh-key: ${{ secrets.DK_MOQUI_ACC_EXTRACTOR }}
          path: './runtime/component/moqui-acc-extractor'
          ref: dtq-dev
      - name: Checkout moqui-projects-api
        uses: actions/checkout@v2
        with:
          repository: dataquest-dev/moqui-projects-api
          ssh-key: ${{ secrets.DK_MOQUI_PROJECTS_API }}
          path: './runtime/component/moqui-projects-api'
          ref: dtq-dev
      - name: Prep - clean database
        run: ./gradlew cleanDb
      - name: Prep - load database
        run: ./gradlew load
      - name: Run unit tests on all components
        run: ./gradlew compTest

# component-test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up JDK
#         uses: actions/setup-java@v2
#         with:
#           java-version: 13
#           distribution: adopt
#       - name: Checkout runtime
#         uses: actions/checkout@v2
#         with:
#           repository: dataquest-dev/moqui-runtime
#           path: './runtime'
#           ref: production
#       - name: Checkout moqui-closure-api
#         uses: actions/checkout@v2
#         with:
#           repository: dataquest-dev/moqui-closure-api
#           ssh-key: ${{ secrets.DK_MOQUI_CLOSURE_API }}
#           path: './runtime/component/moqui-closure-api'
#           ref: master
#       - name: Prep - clean database
#         run: ./gradlew cleanDb
#       - name: Prep - load database
#         run: ./gradlew load
#       - name: Run unit tests on all components
#         run: ./gradlew compTest                                
